# Generated by Django 4.2.1 on 2023-05-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
